# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: postgresql
  database: laterlist_dev
  username: adam
  password: adam

test: &test
  adapter: postgresql
  database: laterlist_test

cucumber:
  <<: *test
